[package]
name = "ming_test_crate"
version = "0.1.0"
edition = "2021"
description = "ming's test crate"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
